### ISSUE TITLE
Expired certificate handling

### ISSUE THREAD

**Issue by AdamISZ** [tlsnotary/pagesigner#11]
User found that a previously validated pagesigner notarization file was shown as invalid in the manager table. Attempting to re-import failed.

After some investigation (for future reference, a user can extract the cert from the pgsg with this script: github.com/tlsnotary/pagesigner-browserless/src/auditee/parse-pgsg.py, usage: `python parse-pgsg.py <path to pgsg file>` , and then extract cert on command line with openssl: `openssl x509 -in 0.der -inform der -text -noout -fingerprint` for example. This script is primitive and can be extended later), we found that the certificate was expired in the meantime.

What's the correct behaviour in this case? The user wants the file to be shown, of course, so we could have a new status for an existing notarization: "expired", but it should not necessarily be seen as a failure mode. It can usually (always?) be verified that the time of the notarization was before the end of the valid period for the certificate by checking the date in the HTTP header of the server response.

**Comment by themighty1** [comment]
Now that the v 1.0.5 oracles return the time of notarization, there can be implementes a check and if the certificate expired after the notarization, then the notarization must be marked valid.

**Comment by AdamISZ** [comment]
Yes, good call.

**Comment by themighty1** [comment]
This has been added in the latest commit
df239ad25b240d9432adcf854b48897a1b83251f
