### ISSUE TITLE
Allow other content types besides HTML

### ISSUE THREAD

**Issue by linagee** [tlsnotary/pagesigner#13]
I'd like to use PageSigner against .zip files. I think this might need to be modified to make this happen? (And likely many other places need to be modified...?)

https://github.com/tlsnotary/pagesigner/blob/master/content/main.js#L281

**Comment by themighty1** [comment]
yes, off the top of my head it should be as easy as adding
else if (header_lines[i].search("zip") > -1){
					type = 'zip';
					break;
				} 

Let me know if this worked.

**Comment by linagee** [comment]
Was able to successfully download my 5MB .zip file using -browserless.
Was able to import it into the Chrome pagesigner extension with this patch against main.js. Without it, I still got the ".html" download.
(And the zip looked intact.)

It still does not appear to work without going to -browserless, but "I think large files are a problem oracle side. I think what makes it work in browserless that doesn't work in browser, can be fixed."

**Comment by themighty1** [comment]
https://github.com/tlsnotary/pagesigner/commit/b86fd2c255f786bae53324c3fe732e891d35ec60
Makes downloading more reliable and add zip support.
If you have a URL to a zip file, paste that URL into Chrome urlbar and then immediately cancel the request (press Stop). After that you can click Notarize... in PageSigner menu.
(Only works in Chrome, Firefox needs to have a bug fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1206557)
