### ISSUE TITLE
PageSigner not working

### ISSUE THREAD

**Issue by traconis** [tlsnotary/pagesigner#18]
Every time I trying to sign a page I getting the same error (Firefox and Chrome)
"You are signing pages to fast. Please retry in 60 sec".
This is the first time I trying to use that extensions - haven't notarize any pages before and waiting one hour doesnt help :(

**Comment by themighty1** [comment]
@traconis  Sorry to hear about your problems
 "You are signing pages to fast. Please retry in 60 sec".
is a generic message which means that our server does not send you any response.

We do not have a one-click way for you to help us troubleshoot your problem.
But I would appreciate it if you did a few steps to help us troubleshoot
In Chrome go to Settings->More Tools->Extensions
An Extensions tab will pop up. There check Developer Mode in top-right corner.

On that tab under PageSigner icon a new link will appear: "background page". Click it
A new window will pop up. Click the Console tab in the top-right corner

After that in your Chrome go to a https page and try to notarize it. When it fails, switch back to the Console window - you will see lots of debug info there.
Please paste that info on a website like http://pastebin.com/ and give us a link to your paste so we could examine the log.
