### ISSUE TITLE
published to store?

### ISSUE THREAD

**Issue by kumavis** [tlsnotary/pagesigner#21]
is this published to the chrome store?

**Comment by kumavis** [comment]
that would be a yes I guess https://chrome.google.com/webstore/detail/pagesigner-helper-app/oclohfdjoojomkfddjclanpogcnjhemd

**Comment by themighty1** [comment]
if you go via the official gateway tlsnotary.org/pagesigner.html , you'll be taken directly to PageSigner. Install it first, then it will ask you to install the helper app (if not already installed)
