### ISSUE TITLE
Firefox is switching to WebExtensions

### ISSUE THREAD

**Issue by myfreeweb** [tlsnotary/pagesigner#24]
The old Firefox extensions API is deprecated. The addon is not currently usable in Firefox Nightly.

It should be possible to turn the Chrome extension into a cross-browser one now, see [Porting a Google Chrome extension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension).

At first glance, `webkitRequestFileSystem` seems like the obvious unsupported API. It's from [a non-standard File and Directory Entries API](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API/Introduction). Firefox has some support for an asynchronous version of that, but it's better to not use an old non-standard API.

**Comment by themighty1** [comment]
Thanks for the heads-up, Im actually in the middle of a switch. The new version should be available within a month.

**Comment by russelldc** [comment]
It appears as though Firefox will be dropping sockets from their extensions API, and Chrome will stop supporting Chrome apps soon.

@themighty1 How do you envision this extension could work without access to sockets?

**Comment by themighty1** [comment]
@russelldc 
My hopes are pretty high that FF will implement socket APIs
In the worst case scenarion, I'll have to create a native app for Win/OSX/Linux which serves as a socket gateway for Pagesigner.

**Comment by cimm** [comment]
Any updates on this?

Firefox "Quantum" has been rolled out now so this extension shows a "Not compatible with Firefox Quantum" error message on the [Firefox Add-ons page](https://addons.mozilla.org/en-GB/firefox/addon/pagesigner/).

**Comment by themighty1** [comment]
For the time being, you'll have to use Firefox ESR or Chrome/ium.
Firefox may implement the needed API. The place to watch is 
https://bugzilla.mozilla.org/show_bug.cgi?id=1247628

**Comment by themighty1** [comment]
No hope of Firefox implementing the API any time soon.
