### ISSUE TITLE
add support for brotli compression algorithm

### ISSUE THREAD

**Issue by mnaboka** [tlsnotary/pagesigner#26]
[Some web pages](https://facebook.com) are using [Brotli](https://en.wikipedia.org/wiki/Brotli) compression algorithm instead of gzip. Example headers from facebook session
```
HTTP/1.1 200 OK
X-XSS-Protection: 0
Pragma: no-cache
content-security-policy: <long string>
Cache-Control: private, no-cache, no-store, must-revalidate
X-Frame-Options: DENY
expect-ct: max-age=10, report-uri="http://reports.fb.com/expectct/"
Strict-Transport-Security: max-age=15552000; preload
X-Content-Type-Options: nosniff
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Accept-Encoding
Content-Encoding: br
Content-Type: text/html; charset=UTF-8
X-FB-Debug: xxxyyyzzz
Date: Thu, 18 Jan 2018 18:36:39 GMT
Transfer-Encoding: chunked
Connection: keep-alive
```
we know that the server is using brotli from this header `Content-Encoding: br` obviously.
The problem happens when i am notarizing the page, my `.pgsg` file contains compressed data instead of plain text.

The workaround for me was to use a [node package](https://www.npmjs.com/package/brotli) to decopress the data into a `Uint8Array` and then [follow the great advise on stackoverflow](https://stackoverflow.com/questions/8936984/uint8array-to-string-in-javascript) to convert Uint8Array to string. This works, but it would be so much better if plugin could do it for you.

**Comment by themighty1** [comment]
Currently PageSigner sends an empty "Accept-Encoding" header which signals to the server to not use any compression at all  which works fine for facebook.com
