### ISSUE TITLE
You are signing pages way too fast. Please retry in 60 seconds

### ISSUE THREAD

**Issue by nachowski** [tlsnotary/pagesigner#29]
> You are signing pages way too fast. Please retry in 60 seconds

Pretty sure I'm not, in fact, signing too fast. Some searching leads me to believe that the EC2 oracle is down. Are there plans to bring it back up or are we expected to use our own oracle servers with the extension?

**Comment by themighty1** [comment]
I assume you are on Chrome, becauase Firefox's Pagesigner addon doesnt work ATM. Pagesigner is working for me on Chrome. There were no plans to take the oracle server offline in the foreseeable future.

**Comment by nachowski** [comment]
Thanks for the quick response! Yes, I'm using the Chrome extension. Turns out the extension was being blocked by an overzealous corporate firewall.
