### ISSUE TITLE
'untrusted certificate'  while certificate is OK

### ISSUE THREAD

**Issue by rsnel** [tlsnotary/pagesigner#30]
Hi all,

Thanks for this great service. I manage her.ovc.nl and I encourage users to take screenshots with PageSigner. Unfortunately it stopped working.

In Chromium and Chrome (on Linux) it says:
"This website cannot be audited by PageSigner because it presented an untrusted certificate."
while the certificate is OK (https://www.sslshopper.com/ssl-checker.html#hostname=her.ovc.nl) I checked the order of the cerficates (as mentioned in issue #12).

In firefox-52.9.0esr (on Linux) (starting up after killing autoupdates by corrupting update-settings.ini) and installing the plugin and restarting it says:
"Cannot notarize because something is wrong with PageSigner server. Please try again later"

Can you help me fix this?

Greetings,

Rik.

**Comment by themighty1** [comment]
Hi and thanks for the feedback,
Unfortunately PageSigner doesnt work on Firefox anymore even if you rollback to the ESR version.

The actual problem is that the root certificate of your website ( DigiCert Global Root G2) is not in the certificate store which PageSigner relies on. PageSigner does have DigiCert Global Root CA but it is a different root certificate.

One workaroud would be to go to the extension console and type in a command and type in:
mustVerifyCert = false
Then the notarization will skip the certificate check and proceed.

**Comment by rsnel** [comment]
Hi,

Thanks for your response.

I did not know how to go to the extension console, so I document a method here:
- select "More tools" -> "Extensions" in the menu
- enable "Developer mode" (upper right)
- click ok "Details" (in the PageSigner tile)
- click on 'background page' (under 'Inspect views')
- click on the 'Console'-tab
- enter: mustVerifyCert = false

This works. 

Can you add "DigiCert Global Root G2" to the PageSigner cerrificate store? As far as I know (and I searched on Google), there is nothing wrong with it (compared to other root certificates, that is).

In the meantime, I'm trying to acquire a version of "DigiCert Global Root G2" signed by "VeriSign Class 3 Public Primary Certification Authority - G5" to make it work seamlessly. (https://community.qualys.com/thread/18356-symantec-distrust-warning-shown-for-new-digicert-certificate)

Greetings,

Rik.

**Comment by themighty1** [comment]
Hi, glad it worked!
PageSigner relies on the certlist maintained by Bitpay here:
https://github.com/bitpay/bitcore-payment-protocol/blob/master/lib/rootcerts.json

I just checked and the most recent version does indeed contain DigiCert Global Root G2.
So during the next PageSigner upgrade, we'll also upgrade the cert store.
Thanks!

**Comment by rsnel** [comment]
Thats great news. Thanks!
