### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by raineorshine** [tlsnotary/pagesigner#32]
When I use the extension in Chrome I get the following error:

```
www.netflix.com is blocked
Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT
```

Chrome Version 80.0.3987.149 (Official Build) (64-bit)
All other extensions disabled.
Testing on netflix.com, dropbox.com

What can I do to troubleshoot? Thanks!

**Comment by themighty1** [comment]
PageSigner2 no longer blocks pages so you should not see this error.
