### ISSUE TITLE
Can't notarize: PageSigner error

### ISSUE THREAD

**Issue by snakebyte85** [tlsnotary/pagesigner#34]
Can't use the extension on any version of Chrome or Chromium, on any page (already tried bitcointalk.org)

The printed message is the following:

`PageSigner error
Cannot notarize because something is wrong with PageSigner server. Please try again later`

Enabled errors on extension and I have these

![2021-01-20_15:45:05](https://user-images.githubusercontent.com/18510364/105190716-96206880-5b36-11eb-8933-01b9944d4734.png)

![2021-01-20_15:45:35](https://user-images.githubusercontent.com/18510364/105190722-9882c280-5b36-11eb-8b37-e9f57b532146.png)

**Comment by themighty1** [comment]
@snakebyte85 , thank you very much. I looked at the log, seems like a problem on AWS's side. Will investigate and seems like we will have to restart the servers and to reupload the extension to the chrome web store. May take a day or two.

**Comment by themighty1** [comment]
@snakebyte85 , everything's been resolved on AWS side, no need to update anything.

**Comment by huey735** [comment]
I get these popups no matter the page I try to notorize. Tried both with Chrome and Brave

![pageSigner001](https://user-images.githubusercontent.com/44140017/109381444-6c472800-78d2-11eb-8245-1b759dcf67c4.png)
![pageSigner002](https://user-images.githubusercontent.com/44140017/109381445-6cdfbe80-78d2-11eb-907b-94aee03d73e7.png)

**Comment by themighty1** [comment]
@huey735 , I really appreciate the heads up!!!
The logs show that on 24 Feb the instance got sporadically rebooted. (AWS does that, I guess)

This means that we will have to set up the server again and update the server's config in the extension. It should be done within 24h. 

I'l post here when it is done.

**Comment by themighty1** [comment]
@huey735 , master branch now has the fix. you can use it already with Chrome's developer mode.
After uploading the new version to chrome web store, it will take a while for it to become available.
