### ISSUE TITLE
PageSigner is not yet able to notarize this website

### ISSUE THREAD

**Issue by huey735** [tlsnotary/pagesigner#36]
Hello. We over at the Bisq Network use PageSigner to verify payments and from time to time we come across the screen bellow. We are thinking about getting a list of urls of banks that give this error so that they can be supported.

What information would you need beside the urls and how would you want it formatted?

![usupportedwebsite](https://user-images.githubusercontent.com/44140017/111126069-30ff5700-856a-11eb-8724-8d9534f7b55f.jpg)

**Comment by themighty1** [comment]
Hi, let's start with a list or URLs, and i'll look at them and see if there may be some quick workarounds to make it work.

**Comment by themighty1** [comment]
@huey735 , any updates on this?

**Comment by themighty1** [comment]
@huey735 , most likely the website doesn't use the AES-GCM ciphersuite which is the only ciphersuite supported by PageSigner (currently). Chacha-Poly can be implemented, potentially.
