### ISSUE TITLE
[question] How does it work?

### ISSUE THREAD

**Issue by mohe2015** [tlsnotary/pagesigner#39]
I'm not an expert with TLS but I don't understand why you need an oracle server. I thought if the client just publishes all the secrets it could prove that the communication actually happened. But I probably have an error in my thought process.

It would be great if you could explain me why and I think it may also be useful if there would be some documentation if it doesn't exist yet.

**Comment by themighty1** [comment]
Good question, on https://tlsnotary.org/ main page there is a diagram which shows the flow.
There is a subtlety: the client alone is not sufficient to prove the communication. The notary must be present.
