### ISSUE TITLE
Any way to sign tweets?

### ISSUE THREAD

**Issue by Jonas-Metzger** [tlsnotary/pagesigner#41]
I noticed that Twitter does not seem to work well with PageSigner. I assume it's because Twitter uses this 'dynamic content' approach. Are you aware of any workaround?

**Comment by themighty1** [comment]
Unfortunately there is no workaround, other than manually finding the exact request which the browser makes (by looking at the network section in the developer console) and notarizing that specific request using pgsg-node cli tool.
Notarizing dynamic content CAN be added to Pagesigner but it requires substantial engineering work.

**Comment by Jonas-Metzger** [comment]
Twitter offers an API that uses TLS. Could I use your cli tool to sign Twitter API get requests? If yes, how would I go about doing that?

**Comment by themighty1** [comment]
Generally speaking, API requests should be easy to sign. 

the cli tool with the instrucions on how to use it is located here https://github.com/tlsnotary/pagesigner/tree/master/webextension/content/pgsg-node

Usually the easiest way is to send the API request using a tool like `curl` and then to ask curl to export the request. Then (with some manual formatting) it would be possible to feed the request to `pgsg-node`.

**Comment by Jonas-Metzger** [comment]
Awesome, thanks a lot! I'll dive into it
