### ISSUE TITLE
Proposal: Move to AssemblyScript to verify+use .pgsg on Ethereum

### ISSUE THREAD

**Issue by Jonas-Metzger** [tlsnotary/pagesigner#45]
I believe PageSigner could become super useful to the Ethereum ecosystem with relatively little extra work.
The idea is to move the code base from JavaScript to [AssemblyScript](https://www.assemblyscript.org/) (a variant of TypeScript, a JS superset), such that it can be compiled to WASM. A self-contained WASM compiled version of the function:

https://github.com/tlsnotary/pagesigner/blob/75fa750e03caba4a65f96a39d31676d4333423ea/webextension/content/main.js#L669

could then be executed via [Truebit](https://truebit.io/) (essentially an optimistic rollup for general-purpose computation on Ethereum, live on mainnet now), which proves to any Ethereum smart contract that a certain website published some information. This essentially soIves the oracle problem for TLS secured web data, which I think would be a killer application for PageSigner. For applications which do not require real-time data feeds, this would be in many ways preferable to what [Chainlink](https://chain.link/) currently offers. I'm in touch with the Truebit Team, who would be very excited about supporting this workflow.

Although I am not familiar with JavaScript or AssemblyScript, I was going to try and port the function above myself because I want to use this solution for a (non-profit) smart contract I'm developing. But since this repo is still actively maintained (which is so awesome by the way!), I assume that there will be further bugfixes coming up. Relying on me (inadequately) porting the bugfixes everytime might not be a sustainable approach to making PageSigner useful to the Ethereum community, so I wanted to ask if you'd be interested in trying (together) to move the whole PageSigner codebase to AssemblyScript once and for all.

**Comment by themighty1** [comment]
Hi, @Jonas-Metzger , thanks for your remarks.
As you correctly said, the TLSNotary protocol on which PageSigner is based is currently work-in-progress.
There will be other features added to it. So, it is difficult to set in stone the pgsg format right now.
We'd be more than happy to discuss any specifics of the implementation in greater detail. Please get in touch at tlsnotarygroup@gmail.com
