### ISSUE TITLE
SOLVED: Signature Forgery via Domain Fronting

### ISSUE THREAD

**Issue by DavidBuchanan314** [tlsnotary/pagesigner#46]
I have forged a signature for `www.google.com`. The PageSigner extension imports, validates, and displays it like so:

![image](https://user-images.githubusercontent.com/13520633/125337129-84ca5300-e346-11eb-8dbb-2a39541a5ff6.png)

The signature file is attached:

[www.google.com.pgsg(1).zip](https://github.com/tlsnotary/pagesigner/files/6803583/www.google.com.pgsg.1.zip)

**Comment by themighty1** [comment]
Hi, @DavidBuchanan314 , thanks for your research.
Could you please describe what you did to accomplish that?

**Comment by DavidBuchanan314** [comment]
The fundamental flaw in PageSigner is that the request headers are not auditable. I'm not sure if there's a way to fix this.

There are a million ways to be sneaky with request headers, to make the response contain "unexpected" content.

In this specific instance, I initiated a valid SSL connection to `www.google.com`, and then made an HTTP request to the host `[my-personal-webserver].translate.goog` (a.k.a Domain Fronting), which in turn proxies the request to my personal webserver.

So technically, PageSigner is correct in saying that "this page was received from www.google.com", but this is misleading.

The majority(?) of websites are hosted behind a CDN that allows domain fronting, in some capacity.

A given website is vulnerable if, for each domain that can be reached via fronting, there exists a domain that hosts/reflects user-generated content.

It is impossible to enumerate all the frontable subdomains, for a given host, and therefore it is impossible to prove whether any PageSigner signature is valid.

**Comment by themighty1** [comment]
Bravo! Great research! 

The request headers WILL be auditable in the new version we are working on. But for now, I'm gonna pin this issue and also post a warning on chrome webstore.

Thank you.

**Comment by DavidBuchanan314** [comment]
Thanks, I look forward to seeing the new version.

**Comment by Jonas-Metzger** [comment]
Very glad you spotted this! 

I'm developing a tool whose security depends on verifying .pgsg's of tweets and of files like [this one ](https://oco2.gesdisc.eosdis.nasa.gov/data/OCO3_DATA/OCO3_L2_Lite_FP.EarlyR/2021/oco3_LtCO2_210101_B10205Xr_210222044620s.nc4.xml) hosted on oco2.gesdisc.eosdis.nasa.gov. Do you expect similar attacks to be possible on these hosts as well?

Haven't heard of domain fronting before, but [domain hiding](https://www.zdnet.com/article/def-con-new-tool-brings-back-domain-fronting-as-domain-hiding/) sounds like a similar more general hack - would this break pagesigner even more?

**Comment by themighty1** [comment]
@Jonas-Metzger , the fundamental issue here is that it is impossible to know whether or not the attack is possible for any domain. 
The mere fact that it is impossible so say with assurance that the attack was NOT possible, cast doubts on any proof generated by PageSigner.

Of course, the verifier can exercise his discretion and say "it is unlikely that a banking website allows domain fronting/hiding, so I will accept the proof as genuine".

Due to this attack, PageSigner can only be used on a case-by-case basis where the verifier understands the risks they are taking in accepting the proof.

**Comment by rjaus** [comment]
I don't know enough about it TBH, I'd only be going off the article linked above.

How's the new version going?  Keen to test it out once you're ready for release.  If you need a beta tester, let me know.

**Comment by themighty1** [comment]
@rjaus , ok, thanks, I'll let you know when it is ready to be tested.

**Comment by rjaus** [comment]
Hey @themighty1 I noticed this repo went up.  Is this related in anyway to the new version you're working on?  I noticed it discusses attesting the entire req/res cycle. Tho it appears limited to publicly accessible url.

**Comment by themighty1** [comment]
Hey @rjaus , PageSigner will rely on URLFetcher's attestation. Currently, the verifier of PageSigner's proof verifies whether the notary server was a properly sandboxed instance by making AWS API calls. With URLFetcher, there is no more need for the verifier to go online to make the API calls, but the verifier can trust the URLFecther attestation.

**Comment by themighty1** [comment]
Hey @rjaus , the updated version is ready for testing here https://github.com/tlsnotary/pagesigner/tree/v3wip
Any comments are welcome in the Discussion section https://github.com/tlsnotary/pagesigner/discussions

**Comment by DavidBuchanan314** [comment]
Could you summarize what has changed, design-wise, in the v3 version? Also, do you have any flow diagrams, similar to the one on the tlsnotary homepage?

**Comment by themighty1** [comment]
I'm gonna need some time to make a write-up about how it works. I'll post here when it is ready.

**Comment by themighty1** [comment]
The new TLSNotary protocol description is available here https://tlsnotary.org/how_it_works.html
This is a full protocol redesign. The diagram is not yet available. PageSigner v3 is based on this new protocol.

**Comment by themighty1** [comment]
PageSigner v3 has been released which fixes this issue.

**Comment by ctrlcctrlv** [comment]
thanks a lot for patching this

https://twitter.com/fr_brennan/status/1545950720670793729
