### ISSUE TITLE
Use the page signer approach, but with an NTS server?

### ISSUE THREAD

**Issue by garyrob** [tlsnotary/PageSigner#48]
Since the NTS (Network Time Security)[1] protocol uses TLS, it occurred to me that perhaps the pagesigner approach could be modified such that, instead of retrieving a web page, the time data is retrieved from a highly-trusted time server, which could be combined with a hash of a document to create a highly-trusted timestamp for the document.

For example, I notice that in pagesigner v3, the request is notarized along with the retrieved page. But it seems like a hash of a document could perhaps be notarized in addition to the request, without huge changes to the existing code.

Would that be feasible?

[1] https://www.internetsociety.org/blog/2020/08/everything-you-need-to-know-about-network-time-security/

**Comment by themighty1** [comment]
Hi, that's a good idea. There only has to be one extra field of 32 bytes for the client's hash which the notary will sign.
UI-wise, seems like this feature is best suited for a CLI tool. (pagesigner v3 CLI is not yet implemented).

**Comment by garyrob** [comment]
In running Pagesigner, I looked at the time supplied by the host from the web page I was notarizing. It appeared that it was a minute or so after I started the notarization process. So that seems to imply that there is considerable preparation time spent before the actual snapshot of the web site  to be notarized is retrieved.

In an ideal world, my hope is that there is a way to say: "Document X came into existence at time xx:xx:xx, to-the-second, and I am notarizing it with a to-the-second timestamp that indicates that." (A second or two later would be fine, but I'd prefer it not to be a minute later.)

Do you think it could be possible to do any preparation in advance of the creation of the document to be timestamped, such that the timestamp could be almost to-the-second?

Also, are you able to estimate how much work would it take to create a CLI tool such as we're discussing (even a version that was only accurate to a minute, if a more instantaneous approach isn't practical)?

**Comment by themighty1** [comment]
Thank for explaining. It would be possible to achieve a to-the-second timestamp if the website supports TLS resumption (which most websites do). The client and the notary would exchange all the 2PC data and perform 2PC computations in advance. The client would then resume a TLS session and immediately send the prepared request to the host.
(you can check with https://www.ssllabs.com/ssltest/index.html if resumption is supported by the host )

The previous CLI version was available here https://github.com/tlsnotary/pagesigner/tree/4ba443bddcb2b7541fee7ad4439d0f1b50474c24/webextension/content/pgsg-node
Should probably take 10 hours or so to change it to work with v3.

**Comment by garyrob** [comment]
There is a web page at www.time.gov, which does provide TLS resumption, but unfortunately when I looked into it further today, it doesn't seem to provide the answer I hoped for. First of all, Using it to provide time to other services is explicitly forbidden. (Also, not that it matters given that restriction, but times do not appear in the HTML as text; it looks like they are somehow provided to the browser in image form.) 

We'd want to use real NTS servers instead of the web page. They also use TLS, but there's a little more to the protocol than that:

"""
The NTS protocol is divided into two-phases. The first phase is the NTS key exchange that establishes the necessary key material between the NTP client and the server. This phase uses the Transport Layer Security (TLS) handshake and relies on the same public key infrastructure as the web. Once the keys are exchanged, the TLS channel is closed and the protocol enters the second phase. In this phase the results of that TLS handshake are used to authenticate NTP time synchronization packets via extension fields. For more information, read RFC 8915
."""

That doesn't sound particularly likely to be usable by TLSNotary. Let me know if I'm wrong!

Maybe there's another web page we could use that doesn't have the legal restrictions and does provide a time snapshot as text. I'll look around. I do think this is a good potential application of your technology, if there's a trustable enough time service that is compatible with it!

**Comment by garyrob** [comment]
However, regardless of my previous post, it still does seem feasible to use the time in the response header returned by web servers. I tried google.com and the www.time.gov server and the response headers on both contained times that agreed with each other and with my computer to-the-second. 

The problem is that no one is guaranteeing that the response headers have accurate timestamps; it just happens that they do. However, if several timestamps were retrieved from web pages from different large entities like Google and the US government, and they all agree, the probability that they ALL just happen to be wrong in exactly the same way is extremely small. (Or maybe more realistically, 10 web sites could be used, and if the majority agree and a couple vary randomly, then the majority time is almost certainly the real time.)

So, my feeling is that timestamps provided in that way would still be very useful. 

Ideally, TLSNotary could be used with real NTS servers (https://gist.github.com/jauderho/2ad0d441760fc5ed69d8d4e2d6b35f8d), because the entities providing them are explicitly trying to provide correct times. But if that isn't possible, this fallback does seem like it could still be very useful.

**Comment by themighty1** [comment]
Upon a cursory look at figure 3 in rfc 8915, it seems like TLSNotary can indeed help half-way up to and including the point where Client Sends TLS application data and receives a Server response. 
Then some NTP-aware tool must parse the server response and craft an NTP Time request and receive a Time response.
Then the Client will commit to this NTP request/response and TLSNotary's notary will release the Server's TLS MAC key to authenticate Server's TLS and NTP responses.
I may be missing some important detail but this is my first impression.

**Comment by garyrob** [comment]
Unless I'm missing something, that half-way help TLSNotary can give is not enough to end up with a result that is notarized in any meaningful sense.

But, notarized response header timestamps do seem to be something TLSNotary could provide, even using Pagesigner as it is, without even making a CLI tool. Am I wrong?

Thank you so much, by the way, for looking into this.

**Comment by garyrob** [comment]
(Although for to-the-second timestamps, modification would be necessary to take advantage of TLS resumption.)

**Comment by themighty1** [comment]
Sure, no problem. Yes, PageSigner v3 notarizes both the request headers and the response headers. Even without the CLI tool, you can manually append the hex of the hash to the URL in the browser URL bar and try to notarize that URL. The server will respond with a 404 error, but it will (hopefully) also include the Date header in the response.
This way you will have the hash in the request and the date in the response both notarized.

**Comment by garyrob** [comment]
Thanks for that feedback! I will experiment and let you know how it goes.

**Comment by garyrob** [comment]
You are right, even when I get a 404 after appending "/<random string>" to the URL, the document generated by TLSNotary does still contain the server's time and the string, at least for the sites I tried.

**Comment by themighty1** [comment]
@garyrob , the cli tool has been reeased https://github.com/tlsnotary/pagesigner-cli

**Comment by garyrob** [comment]
Wow, excellent! Will check it out!

**Comment by garyrob** [comment]
OK, so I tried it on MacOS running node 17.0.1. I created `headers.txt` using the following Python to make sure I had the right line endings:

```
with open("headers.txt", "w") as f:
    f.write("GET / HTTP/1.1\r\n")
    f.write("Host: example.com\r\n\r\n")
```

Then I did:

`./pgsg-node.js notarize example.com --headers headers.txt`


The result ended with the following error. Not sure what I'm doing wrong?

```
server_response.length 593
cert chain verification successful
oracle verification successfully finished
www.example.org example.com
Trace
    at assert (file:///Users/garyrob/Source/test/pagesigner-cli/pagesigner/core/utils.js:137:13)
    at Main.verifyPgsgV6 (file:///Users/garyrob/Source/test/pagesigner-cli/pagesigner/core/Main.js:843:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///Users/garyrob/Source/test/pagesigner-cli/pgsg-node.js:209:49)
Verification successful
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Host not found in certificate".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v17.0.1
```

I tried the potential fix given here: https://github.com/jfromaniello/mac-ca  to no avail.

**Comment by garyrob** [comment]
Next step for me is to try it on Linux... will let you know how it goes

**Comment by themighty1** [comment]
Hmm, I tried your steps and I didnt get the error, I got

server_response.length 1649
cert chain verification successful
oracle verification successfully finished
www.example.org example.com
Session was saved in .... <path/to/session>

The actual error you got was "Host not found in certificate". It means "example.com" was not found in the TLS certificate which the webserver sent. 
The certiificate is being checked against a PageSigner's built-in root store, so changing root stores will not help here.

I guess I'll have to get hold of MacOS and test it out myself some time next week.

**Comment by themighty1** [comment]
Im on Linux btw.

**Comment by garyrob** [comment]
I'm surprised to say that I get exactly the same error ("Host not found in certificate") under Linux Mint (based on Ubuntu), on a different machine. As an aside, I had to do 

`npm install --save node-fetch`

to get it to run at all.

**Comment by themighty1** [comment]
Found the issue. The headers file should have /n instead of /r/n, sorry for the confusion.
"node-fetch" is included in package.json, so it should have been installed automatically when you ran "npm ci". Not sure why it wasn't.

**Comment by garyrob** [comment]
Ah! I thought that when you showed the \r\n twice for the last 2 lines, you were indicating a blank last line, not that the first line shouldn't have the \r. I suggest you change the docs to show the exact invisible characters for each line. On Windows, line endings normally have \r\n, so I didn't assume that the \r would be disallowed at the end of the first line if it was required for the other lines.

Very strange about the node-fetch! If I see this behavior again I'll let you know.

**Comment by themighty1** [comment]
Thank you for your feedback. I pushed a change that saves the user from worrying about newlines in the request.
