### ISSUE TITLE
PageSigner not working on Chrome < 41

### ISSUE THREAD

**Issue by bertani** [tlsnotary/pagesigner#5]
The Chrome extension is not working with Chrome < 41 since the [String.prototype.startsWith method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith)  is not defined

**Comment by AdamISZ** [comment]
Thanks, agreed, also agreed that we should use the Polyfill on that page (although I have no idea how far back that pushes the support).
