### ISSUE TITLE
Chrome Extension Broken

### ISSUE THREAD

**Issue by fabioberger** [tlsnotary/PageSigner#50]
When trying to use PageSigner Chrome Extension on Version 88.0.4324.150 (Official Build) (x86_64) or Version 97.0.4692.71 (Official Build) (x86_64), I was unable to use the extension.

Clicking on it while browsing https://bitcointalk.org causes a tiny white popup to render below the extension icon:

<img width="47" alt="Screenshot 2022-01-13 at 14 13 39" src="https://user-images.githubusercontent.com/97133202/149336653-c9948d6a-be82-431c-9006-0f5d0aff1f40.png">

Nothing else happens. Inspecting the extension does not show any error messages in the console panel. Any idea what's going on?

**Comment by themighty1** [comment]
Hi, @fabioberger , I too have the exact same version  Version 97.0.4692.71 (Official Build) (64-bit) and installing PageSigner from Chrome store on a new profile and running a notarization didn't cause any issues for me.

**Comment by themighty1** [comment]
feel free to reopen if issue persists.

**Comment by fabioberger** [comment]
I deleted the extension and re-installed it and now it's working. Thanks 🙏
