### ISSUE TITLE
Rust implementation

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/PageSigner#51]
Hi, love your project. It is an extremely powerful idea and has a lot of applications. I'm starting a FOSS project inspired by your work, which the Ethereum Foundation is interested in supporting.

We want to implement a similar protocol as a library written in Rust, while targetting WASM for browser support. We are also interested in producing bindings for various languages, such as Python, to increase ease of adoption. Further, we intend to integrate ZK proofs into the protocol for enhanced privacy.

I couldn't find any contact info, but if you are interested in connecting or collaborating, please reach out! Your expertise would be very much appreciated.
email: sinui0@protonmail.com
twitter: @sinuio_

**Comment by themighty1** [comment]
Hi @sinui0 , thanks for reaching out. responded via email.
